language: go
go:
- 1.8.x
before_deploy:
- export PATH=$PATH:$HOME/gopath/bin
- go get github.com/tools/godep
- godep save
deploy:
  provider: heroku
  app: wwm-bb
  skip_cleanup: true
  on:
    repo: WeisswurstSystems/WWM-BB
    branch: master
  api-key:
    secure: gaMYE69WWKREVv0TKP3HC35HhnvYQQ3aZ1LTYtO9zFL5h34XvwiNrXDW/UZnEZxXyV1OnO3WE/Pv6t6jmf6bgel/6+ya47hBPbRUf/PvUZ0VxM0N3XdQxmOgfss3eoXNJfgCyEzjZihVbxlMbTXbjDJrg8kLkZEhLj7OzX+pIm24exBHqXjVuUhIB3cME8ejFNWcEUyjeumye5guXIrDbw+RbM0Q5K2FFzhvsSqboJ/0PkiS4QmAfzpdmjXXcxbZWExI3vzU5w9BGQW9fyfpOGkxH0pFzTIe3ioseuMAuEy5eXJAdQ1KlQews3Iszxd5J2Rgizy9V3xu+neT3hV81Ng25lA+vk+yc7ZenxOmKP7QhhlaidXVqsbac8JMQ+eskO3Tcaz4u8X4QSseKC1fCiJC8MR7E8J9i4Yf2SJsuSxWL12osgLjvKc9Vv7WScLRsBKD87/TdhJFrZ/3Nf6w/UeIXi59Aan2u+MQ/cO7vWXVdaivTBFKQ/jFKGC9wWKkRMNPPUa3BauguYGmE0cYg1mzexx865YyxzT/8OVtuprta00t0etykcQOLjbS903OSo9FCL/hRxMjN1Pex7cbGofdCGrqZ6f0tYFyrTbgSBhLOdQdIHRyz63Uno27JrxMYhgo2jlffaTEy7Ro4kc6UDgvtp8RU0d/GwbX764VgDk=
notifications:
  slack:
    secure: M0HZ5CWd/yNQ7AxuwtxEhiQvBazAgn+hsSReG4X2LTRaVtIauGN4qn6AZmAHjJPRgw3zO0njuQmc12MigrbW5GtSBWkwjLRdyfR5fodVV96o/CLwiqb3vJpUErl+VVgL5e3zjHyC5wkkti5fPBkP/LXF1X1NBvj6+LkturpYplWkIVahf7IxBX7Yn9Bc/YXstE2Y5QMJMAurl3O3U6f+2yLF4/i/nUJayOHoW7wG3IvhUOH/JWTgkIWecwCd3CqXV+lzOGppU+NDbZG2nYsxca1GutQ+NtiT2EwLXzbSxRLFt4R+lBEHADhg1MNTV3Kje6FFH263F0SHKwqWcqjLFIWgX491pFs8uXF44gIeGlBe54bHidYuxtzczltRMZdopc0LLdVuOA39uuqogIAhaulexZGFjzpzKYtzrPUfUxAjO+VjnR3EfR2nmFAaL1HI3rK5bcqtQveib7csO/ehtUHV5a6M+3k7pz0in3mHaemTk3cuGfLvypBuvtsMLybL1hGuFJoMjYhgSlkl1xPiLdkhBBctxZqKN4gr5nbZy3HDfJ+A5yx78nVZKycgz4nQcY4yohoXEt90HUOaUUHBPmn5NRMZ6H3aRQnEUkJc62cPH+K30KMSEMFyOx1eD79UIMtmro30tYHWax48qQZ7R4PqNkAnYGfeK4lf85U8qbA=
