language: go
go:
- 1.8.x
deploy:
  provider: heroku
  api_key:
    secure: jWKfd2+/XFbI5HV/PcBcqmlECE3lS25PNOe+XYmp6cLIwhIXEc9Ovt6dhEwZwa5qNrtMY/8sU5Durv4G8XnGpx00hmlZHtCy282VPRTG/MY8/8/tD2wMbhIhnm8mN/k//4xgUi4tWlAHGK3TXD8ncEMEs2DdKS0srZdsTTTZo1KneBHvOArwuLE6g7ABvEJ1hs/SGGe4Wo2tdwK3FGvbxHVJylQ+GdVXzSUrNotxwiQS9NoYfPTct9wAkrsKrJFCDfs7/dTMA9Xhh6z0IIStHPPBjTBTBlgL8D0JFkXfOzDgZNOxyhLKiB+sfTAxkFFn7pP+V6Tncb76MZrCgbQxrQtA69drP5hSP98mZTnBOFsuuWQdze0mrMWoJa07nZioSoiqb2ZvbRhK7OFmGYNFwBduV3WDe6X3NCiuXz2A8yrM/xD1lQW0tO5FFlmDfxOo/l2z3a2tMyxEQZlMdAnyIpRkOm1pIJT96/CA5tA87o+zeRDD5YCgjEKV8/E7SALqrRMYAfh4EzeoZFM2jiawJMThIyo9oYhb4grwWbmsdQCBcOdxpz0UhpibdKLiWLORj5lzQF5C/JVmFQaSgUgGwbDXJjERh3y+Vo4Dx9wIepal13iRaZQP6dHTqCqsfVlsI3PSnEovpw401X+zUQCQrzPZhASv9GuMcHGmO2UBbB8=
