language: go
go:
- 1.8.x
deploy:
  provider: heroku
  app: wwm-bb
  on:
    repo: WeisswurstSystems/WWM-BB
  api-key:
    secure: gaMYE69WWKREVv0TKP3HC35HhnvYQQ3aZ1LTYtO9zFL5h34XvwiNrXDW/UZnEZxXyV1OnO3WE/Pv6t6jmf6bgel/6+ya47hBPbRUf/PvUZ0VxM0N3XdQxmOgfss3eoXNJfgCyEzjZihVbxlMbTXbjDJrg8kLkZEhLj7OzX+pIm24exBHqXjVuUhIB3cME8ejFNWcEUyjeumye5guXIrDbw+RbM0Q5K2FFzhvsSqboJ/0PkiS4QmAfzpdmjXXcxbZWExI3vzU5w9BGQW9fyfpOGkxH0pFzTIe3ioseuMAuEy5eXJAdQ1KlQews3Iszxd5J2Rgizy9V3xu+neT3hV81Ng25lA+vk+yc7ZenxOmKP7QhhlaidXVqsbac8JMQ+eskO3Tcaz4u8X4QSseKC1fCiJC8MR7E8J9i4Yf2SJsuSxWL12osgLjvKc9Vv7WScLRsBKD87/TdhJFrZ/3Nf6w/UeIXi59Aan2u+MQ/cO7vWXVdaivTBFKQ/jFKGC9wWKkRMNPPUa3BauguYGmE0cYg1mzexx865YyxzT/8OVtuprta00t0etykcQOLjbS903OSo9FCL/hRxMjN1Pex7cbGofdCGrqZ6f0tYFyrTbgSBhLOdQdIHRyz63Uno27JrxMYhgo2jlffaTEy7Ro4kc6UDgvtp8RU0d/GwbX764VgDk=
