language: go
go:
- 1.8.x
deploy:
  provider: heroku
  api_key:
    secure: MWlryh11DIo8Iwchfr73CvZV38kUUaQCNMoTQKhIqRwvW7XsRbDuoZVh5zfRCBIA/53tgNIqKYnpzSwlzV9C3F/t9H4sJAsBa1mZYmBH/X4/R7C81RNVqBIlMJaQA1jJlhdVLgxOieehO3ZQg2mO1PT2usOBfpWO3RsOHcJ49ah5TCFqVYla3x6qM8UPRy9yNJk4tcx6/sxLuGFL7DCTtL5Z4nh5AcSui8TBevtmz2Y91YoQeUaTIIGpepLpoGWyOCd6l1DS/Jcx154BR9P+rvTW0djPsqU+cH6YdLZhtS5vAh1nDWa4beKfwTmHXEypd12qzHnkCyxC5j8JcZZiW4Ok9ZAq1nWe1wXR7OR4zP7ZJkUsoXdqFyfZHxLsyw7OxyU97dQzUTE2ZDImiQzgJ0buMch1vwj+U7l8F6DNob64BYGGRiTqC9LLpTQ20Q3HzgMxDXEK3OQ4rHGuI24S3puc8qzuGH7r6nX5BCtRjRJQ50NsT5Trc3EHpXPQ+xtVu7vMAvNe8nO55pl4isPObSKQ5alQwXc3k5uxj9TWUDtEDm1gxkJkdywXN0vPAgF1HpTVvdv/HHmj3k7FAOxaVNJudCcNIBBgn1K1P0T028WR+NMfSRIkA8nGAlBZF8lcsIQTCdt6T16NX/hf3L1Ynlh4nYIecfCn+/N4dw8copI=