language: go
go:
- 1.8.x
deploy:
  provider: heroku
  api_key:
    secure: nEXW6TMUPrjbqMSwt91xtHD6/DjF5f7A4GXTxw4DNo0JDa4IXqmU/QhcEk2Y7hdktJxUvnYmSo/5Ft4iKAaZBOiFXu/eWwpECLWhucw1eqd8pzs4lO6cYnRybzNW/jQIV7SZTidPW/2q91Pg71ObalOwvc1VEUpsjqo0QrmdWyydjX/VJpowZZZcigljVfG36xDoSYMe5utljHqiL5GiJRfzaOiUBHYmz4Dct9CsffKC2rpPa8IfcxBqy8NbP9raH6cN/A8kGVZ9D/wxFZYo1sXDnuYg6/sx67zMTiuEQbHY/tfYlAlOGxrSQ344RndOHbFeZlVyRr0f9OHQyEkhXiIqFs9Ya/6tlTFJWMYSpL0VX1LLFda5IWuVayHXhJa77yZPn7RYYPWddbOvpjwbrOyRRdiY9+2Jyo2lYKtduLc3yoxhS58Zou2qI/rrjGtpOBYBe4pTtjwhvDHKTYydv0tVawDyWHORbTftfo0v3+72GlDjVfHVeWuXt/uhS0Xm+zD353lm5tdmW4mGLxg3DlpOLmyH/c7Rl63bfXkpuTBRu+d/Fc7etXHmxRzt+mH9Td+VCKE2375kl4QhQdK6+7yAG5rA4cJeoWzxvDUyjLVl8YBlGcvIqGC2QKExAJsTVVoPohhMVYEI4F3spvS0WySE10D9DC0OzibkA/qNA68=
  app: wwm-bb
  on:
    repo: WeisswurstSystems/WWM-BB
