language: go
go:
- 1.8.x
deploy:
  provider: heroku
  api_key:
    secure: LwgrcRwa7Q6Bkg0qYVQb78wsW2dwb7lq2Svrj7z5jqnrVYfYazVABMJRYdInSeowxJLFNdLYXibP9HHMt7X/Q70WmuYwwEnjtcBZMxu1iGlbV1odsNcs37Yxm2/wzQMeFDQPyvaMT7CQhZ5VtDdIEuu7ksP8XAT/NZABCGGWuGifMdamSwbV68e2NlFN7+h+1669nHqHtbhcXNbOTGEpHF/11Dmfq0vLE7gn14q68GQc4HPhf2DgWHYzx8j80Q8nJ3coOZj8NxTHlbL9w4jg7hUwsRdV0m+ahe/H3jEIlCWFgE0wuGeVtdBUcBUgjBKtNhUX3Et3Lc7w3kawRIUEH6Z9h5QUEEJlQxwgApmNL9UKtSAKaZsM5/YmjfqqqMuaST3j5ekzvynCSa5f+VvGLW9yijVrweLFexCbhDVGHAIVAz+KWZyWNDI48Q16VZCpPqNqmhzPJD4GItjcjLfTiThpnjAoMOfRrl/hgpm/XTCVC2+XVvYeu5ZNY4XOxeBwvmUDxfAU/ayxvR7wVFfpPe3oIezZEF7T8Z0dNgXctkw0Vuw7KedeybXZBAPvTuPdNpS2LmCBu8oyPvBDDzDOkGFw0ByWIHeUQhhMi6+HMR7P4NY8/oCaXJpaekaao1Pn6b6bdbBqf1EbYHINpUZVTK2t3FrVheGCSUAOHyUekW0=